final doctorMapList = [
  {
    "name": "Dr. Poonam Bhatia",
    "type": "Consultant-Gynaecology & Obstetrics",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/swati.jpg",
    "description": "She is a Consultant in the department of Obstertrics and gynaecology at sant Parmanand hospital,delhi. Her area of expertise include diagnosing and treating gynaecological disorders like PCOS,ovarian cysts,uterine fibroids, menstruation problems among many others.She has experience treating women of all age groups with a special interest in managing hormonal disbalances and disorders.",
  },
  {
    "name": "Dr. Punita Arora",
    "type": "Senior Consultant-Gynaecology & Obstetrics",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/adhya.jpg",
    "description": "Dr.Punita Arora is a renowed Gynaecologist in Gurgaon. For the past 35 years, Dr.Punita has worked as Gynaecologist, Obstetrician and gained proficient skills and knowledge in the segments.",
  },
  {
    "name": "Dr. Sanjeev Mohapatra",
    "type": "Dermatologist",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image":"assets/sinha.jpg",
    "description": "Dr. Sanjeev Mohapatra is the Medical Director at SKINOS. All treatments done here are USA FDA approved. He believes in evidence-based and purely ethical practice. Here you can be fully assured of right and accurate management completely as per medical guidelines. His simplicity, compassionate nature, and easy approach-ability have what gained his thousands of patients cum friends not only in Delhi but across India. ",
  },
  {
    "name": "Dr. A.K. Bhargava",
    "type": "Dietician",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image":"assets/dietician.jpg",
    "description": "She is a popular dietitian in Hyderabad. She provides solutions for weight loss, fat loss, reduces belly/ tummy fat, weight gain, gains muscle mass, diet in pregnancy and lactation, pediatrics, diabetic diet, hypertension, cardiovascular, renal issues, bariatrics, cancer, sports nutrition, PCOD, PCOS.",
  }
];
